# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aa5ce10101f6197e7e277c39fd8b0570bbc660dc55fa93b4810785138283f40b2640461aa1756af8f4083b97dd09d8b9bd1deb3749914dd9c2f3e9e4f87f9d5

test:
  secret_key_base: 12313fb86bcc5a54d7cb052ac2c2b0fa8ccde96b7f24eab624425f53e85000fadc2afeb714ad7db7930e3795c10d993e7109d3a63717596f61b17dae47f37198

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
